### ISSUE TITLE
Milestone 0

### ISSUE THREAD

**Issue by JonahWeaver** [JonahWeaver/Tactics-Game#2]
#### Milestone 0 
- [x] Fix camera initial position
- [x] Optimize Tile Generation and boot-up
- [ ] Complete Battle Menu
- [ ] ^Present only applicable menu options
- [ ] ^Finish button function implementation
- [ ] Complete Inventory Functionality
- [ ] Fix Turn Manager
- [ ] ^Intuitive variables
- [ ] ^Battle end and Transitioning
- [ ] Editor Script Framework
- [ ] ^ObjectDataManager
- [ ] ^Dynamic Data Serializing

**v0.0.1**
